project:
  type: book

date: 12/14/2023
date-modified: today

book:
  cookie-consent: implied
  google-analytics: G-0S02BWQ0DX
  title: "Métropole d'Aix Marseille Provence"
  subtitle: "Premiers résultats"
  cover-image: images/Marseille_-_vieille_carte.jpg
  author:
    - name: Xavier Timbeau
    - name: Maxime Parodi
    - name: Scotia Hille
  navbar: false
  page-navigation: true
  back-to-top-navigation: true
  tools:
    - icon: github
      href: https://github.com/xtimbeau/marseille/
  comments: 
    utterances:
      repo: xtimbeau/marseille
  page-footer:
    left: "*Premiers résultats, ne pas diffuser*"
    right: "**CC BY 4.0**"
  chapters:
    - index.qmd
    - localisations.qmd
    - accessibilites.qmd
    - trajets.qmd
    - next.qmd
    - commerces.qmd
    
execute: 
  freeze: false
  echo: false
  warning: false
  
bibliography: references.bib

lang: fr

format:
  ofce-html: default

editor: visual