# Prochaines étapes

-   {{< fa check >}} Générations des géométries

-   {{< fa check >}} Projection des emplois et des actifs MOBPRO selon les fichiers fonciers

-   {{< fa check >}} Données de réseaux routiers et GTFS

-   {{< fa check >}} Calcul des distances avec les routeurs

-   {{< fa check >}} Calcul de l'accessibilité pour 4 modes, cartes

-   {{< fa check >}} Génération des flux carreau carreau par MEAPS (et par un modèle gravitaire)

-   {{< fa check >}} Estimation d'un modèle MEAPS sur MOPBRO, comparaison avec La Rochelle

-   {{< fa check >}} Projection, sur la base de l'EMP 2019, des km par habitant

-   {{< iconify ri progress-3-line >}} Estimation sur la base EMC^2^ metAM des modèles de projection, comparaison avec EMP 2019

-   Autres motifs

    -   Ecole/études à partir de MOBSCOL

    -   {{< fa check >}} Commerces à partir de la densité de commerces (fichiers fonciers) ou de la densité inversée (accessibilité aux personnes)

    -   Autres motifs en se calant sur la densité de personnes

    -   {{< fa check >}} L'accès aux informations de localisation de l'EMC^2^ aide beaucoup

-   Intégration de la congestion

    -   {{< iconify mdi cancel-outline >}} Couche mapbox trafic usuel, données jusqu'au segment, pas de temps 5 minutes pour un jour type. Facile à intégrer dans nos analyses de flux. Coût de 20k€ pour la zone AMP. *Décision de ne pas acquérir les données Mapbox.*

    -   {{< iconify gravity-ui eyes-look-left >}} Autres données de trafic (HEAR/HERE, WAZE, extractions mapbox spécifiques, Google, SETEC). Coût de traitement important
    
    -   {{< iconify gravity-ui eyes-look-left >}} Données Orange Coldefy Lévy. Flux estimés à partir des bornages, au niveau de l'IRIS. Coût de traitement important, plusieurs mois avant la disponibilité (conditionel à l'ANR Géokinésys.

    -   Générations de flux à partir de MEAPS et dodgr (en particulier pour les scénarios)
